/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as Char123LocaleChar125RouteRouteImport } from './routes/{-$locale}/route'
import { Route as Char123LocaleChar125rootLayoutRouteRouteImport } from './routes/{-$locale}/(root-layout)/route'
import { Route as Char123LocaleChar125consoleLayoutRouteRouteImport } from './routes/{-$locale}/(console-layout)/route'
import { Route as Char123LocaleChar125centeredLayoutRouteRouteImport } from './routes/{-$locale}/(centered-layout)/route'
import { Route as Char123LocaleChar125adminLayoutRouteRouteImport } from './routes/{-$locale}/(admin-layout)/route'
import { Route as Char123LocaleChar125rootLayoutIndexRouteImport } from './routes/{-$locale}/(root-layout)/index'
import { Route as ApiHealthLiveRouteImport } from './routes/[_]api/health/live'
import { Route as Char123LocaleChar125rootLayoutauthRouteRouteImport } from './routes/{-$locale}/(root-layout)/(auth)/route'
import { Route as Char123LocaleChar125centeredLayoutguestRouteRouteImport } from './routes/{-$locale}/(centered-layout)/(guest)/route'
import { Route as Char123LocaleChar125rootLayoutTermsOfServiceIndexRouteImport } from './routes/{-$locale}/(root-layout)/terms-of-service/index'
import { Route as Char123LocaleChar125rootLayoutStatusIndexRouteImport } from './routes/{-$locale}/(root-layout)/status/index'
import { Route as Char123LocaleChar125rootLayoutPrivacyPolicyIndexRouteImport } from './routes/{-$locale}/(root-layout)/privacy-policy/index'
import { Route as Char123LocaleChar125rootLayoutPricingIndexRouteImport } from './routes/{-$locale}/(root-layout)/pricing/index'
import { Route as Char123LocaleChar125rootLayoutPlaygroundIndexRouteImport } from './routes/{-$locale}/(root-layout)/playground/index'
import { Route as Char123LocaleChar125rootLayoutErrorIndexRouteImport } from './routes/{-$locale}/(root-layout)/error/index'
import { Route as Char123LocaleChar125rootLayoutChangelogIndexRouteImport } from './routes/{-$locale}/(root-layout)/changelog/index'
import { Route as Char123LocaleChar125rootLayoutAboutIndexRouteImport } from './routes/{-$locale}/(root-layout)/about/index'
import { Route as Char123LocaleChar125consoleLayoutAppIndexRouteImport } from './routes/{-$locale}/(console-layout)/app/index'
import { Route as Char123LocaleChar125adminLayoutAdminIndexRouteImport } from './routes/{-$locale}/(admin-layout)/admin/index'
import { Route as Char123LocaleChar125rootLayoutauthOnboardingIndexRouteImport } from './routes/{-$locale}/(root-layout)/(auth)/onboarding/index'
import { Route as Char123LocaleChar125rootLayoutauthDashboardIndexRouteImport } from './routes/{-$locale}/(root-layout)/(auth)/dashboard/index'
import { Route as Char123LocaleChar125consoleLayoutAppWebhooksIndexRouteImport } from './routes/{-$locale}/(console-layout)/app/webhooks/index'
import { Route as Char123LocaleChar125consoleLayoutAppTeamIndexRouteImport } from './routes/{-$locale}/(console-layout)/app/team/index'
import { Route as Char123LocaleChar125consoleLayoutAppSettingsIndexRouteImport } from './routes/{-$locale}/(console-layout)/app/settings/index'
import { Route as Char123LocaleChar125consoleLayoutAppSecurityIndexRouteImport } from './routes/{-$locale}/(console-layout)/app/security/index'
import { Route as Char123LocaleChar125consoleLayoutAppProfileIndexRouteImport } from './routes/{-$locale}/(console-layout)/app/profile/index'
import { Route as Char123LocaleChar125consoleLayoutAppNotificationsIndexRouteImport } from './routes/{-$locale}/(console-layout)/app/notifications/index'
import { Route as Char123LocaleChar125consoleLayoutAppFeaturesIndexRouteImport } from './routes/{-$locale}/(console-layout)/app/features/index'
import { Route as Char123LocaleChar125consoleLayoutAppBillingIndexRouteImport } from './routes/{-$locale}/(console-layout)/app/billing/index'
import { Route as Char123LocaleChar125consoleLayoutAppBatchJobsIndexRouteImport } from './routes/{-$locale}/(console-layout)/app/batch-jobs/index'
import { Route as Char123LocaleChar125consoleLayoutAppAuditIndexRouteImport } from './routes/{-$locale}/(console-layout)/app/audit/index'
import { Route as Char123LocaleChar125consoleLayoutAppApiKeysIndexRouteImport } from './routes/{-$locale}/(console-layout)/app/api-keys/index'
import { Route as Char123LocaleChar125consoleLayoutAppAiUsageIndexRouteImport } from './routes/{-$locale}/(console-layout)/app/ai-usage/index'
import { Route as Char123LocaleChar125centeredLayoutguestSignInIndexRouteImport } from './routes/{-$locale}/(centered-layout)/(guest)/sign-in/index'
import { Route as Char123LocaleChar125centeredLayoutguestResetPasswordIndexRouteImport } from './routes/{-$locale}/(centered-layout)/(guest)/reset-password/index'
import { Route as Char123LocaleChar125centeredLayoutguestForgotPasswordIndexRouteImport } from './routes/{-$locale}/(centered-layout)/(guest)/forgot-password/index'
import { Route as Char123LocaleChar125centeredLayoutguestCreateAnAccountIndexRouteImport } from './routes/{-$locale}/(centered-layout)/(guest)/create-an-account/index'
import { Route as Char123LocaleChar125centeredLayoutguestAcceptInviteIndexRouteImport } from './routes/{-$locale}/(centered-layout)/(guest)/accept-invite/index'
import { Route as Char123LocaleChar125adminLayoutAdminWorkspacesIndexRouteImport } from './routes/{-$locale}/(admin-layout)/admin/workspaces/index'
import { Route as Char123LocaleChar125adminLayoutAdminUsersIndexRouteImport } from './routes/{-$locale}/(admin-layout)/admin/users/index'
import { Route as Char123LocaleChar125adminLayoutAdminSettingsIndexRouteImport } from './routes/{-$locale}/(admin-layout)/admin/settings/index'
import { Route as Char123LocaleChar125adminLayoutAdminPlansIndexRouteImport } from './routes/{-$locale}/(admin-layout)/admin/plans/index'
import { Route as Char123LocaleChar125adminLayoutAdminFeaturesIndexRouteImport } from './routes/{-$locale}/(admin-layout)/admin/features/index'
import { Route as Char123LocaleChar125adminLayoutAdminEmailsIndexRouteImport } from './routes/{-$locale}/(admin-layout)/admin/emails/index'
import { Route as Char123LocaleChar125adminLayoutAdminAuditIndexRouteImport } from './routes/{-$locale}/(admin-layout)/admin/audit/index'
import { Route as Char123LocaleChar125adminLayoutAdminWorkspacesIdIndexRouteImport } from './routes/{-$locale}/(admin-layout)/admin/workspaces/$id/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125RouteRoute =
  Char123LocaleChar125RouteRouteImport.update({
    id: '/{-$locale}',
    path: '/{-$locale}',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125rootLayoutRouteRoute =
  Char123LocaleChar125rootLayoutRouteRouteImport.update({
    id: '/(root-layout)',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125consoleLayoutRouteRoute =
  Char123LocaleChar125consoleLayoutRouteRouteImport.update({
    id: '/(console-layout)',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125centeredLayoutRouteRoute =
  Char123LocaleChar125centeredLayoutRouteRouteImport.update({
    id: '/(centered-layout)',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125adminLayoutRouteRoute =
  Char123LocaleChar125adminLayoutRouteRouteImport.update({
    id: '/(admin-layout)',
    getParentRoute: () => Char123LocaleChar125RouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutIndexRoute =
  Char123LocaleChar125rootLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125rootLayoutRouteRoute,
  } as any)
const ApiHealthLiveRoute = ApiHealthLiveRouteImport.update({
  id: '/_api/health/live',
  path: '/_api/health/live',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125rootLayoutauthRouteRoute =
  Char123LocaleChar125rootLayoutauthRouteRouteImport.update({
    id: '/(auth)',
    getParentRoute: () => Char123LocaleChar125rootLayoutRouteRoute,
  } as any)
const Char123LocaleChar125centeredLayoutguestRouteRoute =
  Char123LocaleChar125centeredLayoutguestRouteRouteImport.update({
    id: '/(guest)',
    getParentRoute: () => Char123LocaleChar125centeredLayoutRouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutTermsOfServiceIndexRoute =
  Char123LocaleChar125rootLayoutTermsOfServiceIndexRouteImport.update({
    id: '/terms-of-service/',
    path: '/terms-of-service/',
    getParentRoute: () => Char123LocaleChar125rootLayoutRouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutStatusIndexRoute =
  Char123LocaleChar125rootLayoutStatusIndexRouteImport.update({
    id: '/status/',
    path: '/status/',
    getParentRoute: () => Char123LocaleChar125rootLayoutRouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutPrivacyPolicyIndexRoute =
  Char123LocaleChar125rootLayoutPrivacyPolicyIndexRouteImport.update({
    id: '/privacy-policy/',
    path: '/privacy-policy/',
    getParentRoute: () => Char123LocaleChar125rootLayoutRouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutPricingIndexRoute =
  Char123LocaleChar125rootLayoutPricingIndexRouteImport.update({
    id: '/pricing/',
    path: '/pricing/',
    getParentRoute: () => Char123LocaleChar125rootLayoutRouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutPlaygroundIndexRoute =
  Char123LocaleChar125rootLayoutPlaygroundIndexRouteImport.update({
    id: '/playground/',
    path: '/playground/',
    getParentRoute: () => Char123LocaleChar125rootLayoutRouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutErrorIndexRoute =
  Char123LocaleChar125rootLayoutErrorIndexRouteImport.update({
    id: '/error/',
    path: '/error/',
    getParentRoute: () => Char123LocaleChar125rootLayoutRouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutChangelogIndexRoute =
  Char123LocaleChar125rootLayoutChangelogIndexRouteImport.update({
    id: '/changelog/',
    path: '/changelog/',
    getParentRoute: () => Char123LocaleChar125rootLayoutRouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutAboutIndexRoute =
  Char123LocaleChar125rootLayoutAboutIndexRouteImport.update({
    id: '/about/',
    path: '/about/',
    getParentRoute: () => Char123LocaleChar125rootLayoutRouteRoute,
  } as any)
const Char123LocaleChar125consoleLayoutAppIndexRoute =
  Char123LocaleChar125consoleLayoutAppIndexRouteImport.update({
    id: '/app/',
    path: '/app/',
    getParentRoute: () => Char123LocaleChar125consoleLayoutRouteRoute,
  } as any)
const Char123LocaleChar125adminLayoutAdminIndexRoute =
  Char123LocaleChar125adminLayoutAdminIndexRouteImport.update({
    id: '/admin/',
    path: '/admin/',
    getParentRoute: () => Char123LocaleChar125adminLayoutRouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutauthOnboardingIndexRoute =
  Char123LocaleChar125rootLayoutauthOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => Char123LocaleChar125rootLayoutauthRouteRoute,
  } as any)
const Char123LocaleChar125rootLayoutauthDashboardIndexRoute =
  Char123LocaleChar125rootLayoutauthDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => Char123LocaleChar125rootLayoutauthRouteRoute,
  } as any)
const Char123LocaleChar125consoleLayoutAppWebhooksIndexRoute =
  Char123LocaleChar125consoleLayoutAppWebhooksIndexRouteImport.update({
    id: '/app/webhooks/',
    path: '/app/webhooks/',
    getParentRoute: () => Char123LocaleChar125consoleLayoutRouteRoute,
  } as any)
const Char123LocaleChar125consoleLayoutAppTeamIndexRoute =
  Char123LocaleChar125consoleLayoutAppTeamIndexRouteImport.update({
    id: '/app/team/',
    path: '/app/team/',
    getParentRoute: () => Char123LocaleChar125consoleLayoutRouteRoute,
  } as any)
const Char123LocaleChar125consoleLayoutAppSettingsIndexRoute =
  Char123LocaleChar125consoleLayoutAppSettingsIndexRouteImport.update({
    id: '/app/settings/',
    path: '/app/settings/',
    getParentRoute: () => Char123LocaleChar125consoleLayoutRouteRoute,
  } as any)
const Char123LocaleChar125consoleLayoutAppSecurityIndexRoute =
  Char123LocaleChar125consoleLayoutAppSecurityIndexRouteImport.update({
    id: '/app/security/',
    path: '/app/security/',
    getParentRoute: () => Char123LocaleChar125consoleLayoutRouteRoute,
  } as any)
const Char123LocaleChar125consoleLayoutAppProfileIndexRoute =
  Char123LocaleChar125consoleLayoutAppProfileIndexRouteImport.update({
    id: '/app/profile/',
    path: '/app/profile/',
    getParentRoute: () => Char123LocaleChar125consoleLayoutRouteRoute,
  } as any)
const Char123LocaleChar125consoleLayoutAppNotificationsIndexRoute =
  Char123LocaleChar125consoleLayoutAppNotificationsIndexRouteImport.update({
    id: '/app/notifications/',
    path: '/app/notifications/',
    getParentRoute: () => Char123LocaleChar125consoleLayoutRouteRoute,
  } as any)
const Char123LocaleChar125consoleLayoutAppFeaturesIndexRoute =
  Char123LocaleChar125consoleLayoutAppFeaturesIndexRouteImport.update({
    id: '/app/features/',
    path: '/app/features/',
    getParentRoute: () => Char123LocaleChar125consoleLayoutRouteRoute,
  } as any)
const Char123LocaleChar125consoleLayoutAppBillingIndexRoute =
  Char123LocaleChar125consoleLayoutAppBillingIndexRouteImport.update({
    id: '/app/billing/',
    path: '/app/billing/',
    getParentRoute: () => Char123LocaleChar125consoleLayoutRouteRoute,
  } as any)
const Char123LocaleChar125consoleLayoutAppBatchJobsIndexRoute =
  Char123LocaleChar125consoleLayoutAppBatchJobsIndexRouteImport.update({
    id: '/app/batch-jobs/',
    path: '/app/batch-jobs/',
    getParentRoute: () => Char123LocaleChar125consoleLayoutRouteRoute,
  } as any)
const Char123LocaleChar125consoleLayoutAppAuditIndexRoute =
  Char123LocaleChar125consoleLayoutAppAuditIndexRouteImport.update({
    id: '/app/audit/',
    path: '/app/audit/',
    getParentRoute: () => Char123LocaleChar125consoleLayoutRouteRoute,
  } as any)
const Char123LocaleChar125consoleLayoutAppApiKeysIndexRoute =
  Char123LocaleChar125consoleLayoutAppApiKeysIndexRouteImport.update({
    id: '/app/api-keys/',
    path: '/app/api-keys/',
    getParentRoute: () => Char123LocaleChar125consoleLayoutRouteRoute,
  } as any)
const Char123LocaleChar125consoleLayoutAppAiUsageIndexRoute =
  Char123LocaleChar125consoleLayoutAppAiUsageIndexRouteImport.update({
    id: '/app/ai-usage/',
    path: '/app/ai-usage/',
    getParentRoute: () => Char123LocaleChar125consoleLayoutRouteRoute,
  } as any)
const Char123LocaleChar125centeredLayoutguestSignInIndexRoute =
  Char123LocaleChar125centeredLayoutguestSignInIndexRouteImport.update({
    id: '/sign-in/',
    path: '/sign-in/',
    getParentRoute: () => Char123LocaleChar125centeredLayoutguestRouteRoute,
  } as any)
const Char123LocaleChar125centeredLayoutguestResetPasswordIndexRoute =
  Char123LocaleChar125centeredLayoutguestResetPasswordIndexRouteImport.update({
    id: '/reset-password/',
    path: '/reset-password/',
    getParentRoute: () => Char123LocaleChar125centeredLayoutguestRouteRoute,
  } as any)
const Char123LocaleChar125centeredLayoutguestForgotPasswordIndexRoute =
  Char123LocaleChar125centeredLayoutguestForgotPasswordIndexRouteImport.update({
    id: '/forgot-password/',
    path: '/forgot-password/',
    getParentRoute: () => Char123LocaleChar125centeredLayoutguestRouteRoute,
  } as any)
const Char123LocaleChar125centeredLayoutguestCreateAnAccountIndexRoute =
  Char123LocaleChar125centeredLayoutguestCreateAnAccountIndexRouteImport.update(
    {
      id: '/create-an-account/',
      path: '/create-an-account/',
      getParentRoute: () => Char123LocaleChar125centeredLayoutguestRouteRoute,
    } as any,
  )
const Char123LocaleChar125centeredLayoutguestAcceptInviteIndexRoute =
  Char123LocaleChar125centeredLayoutguestAcceptInviteIndexRouteImport.update({
    id: '/accept-invite/',
    path: '/accept-invite/',
    getParentRoute: () => Char123LocaleChar125centeredLayoutguestRouteRoute,
  } as any)
const Char123LocaleChar125adminLayoutAdminWorkspacesIndexRoute =
  Char123LocaleChar125adminLayoutAdminWorkspacesIndexRouteImport.update({
    id: '/admin/workspaces/',
    path: '/admin/workspaces/',
    getParentRoute: () => Char123LocaleChar125adminLayoutRouteRoute,
  } as any)
const Char123LocaleChar125adminLayoutAdminUsersIndexRoute =
  Char123LocaleChar125adminLayoutAdminUsersIndexRouteImport.update({
    id: '/admin/users/',
    path: '/admin/users/',
    getParentRoute: () => Char123LocaleChar125adminLayoutRouteRoute,
  } as any)
const Char123LocaleChar125adminLayoutAdminSettingsIndexRoute =
  Char123LocaleChar125adminLayoutAdminSettingsIndexRouteImport.update({
    id: '/admin/settings/',
    path: '/admin/settings/',
    getParentRoute: () => Char123LocaleChar125adminLayoutRouteRoute,
  } as any)
const Char123LocaleChar125adminLayoutAdminPlansIndexRoute =
  Char123LocaleChar125adminLayoutAdminPlansIndexRouteImport.update({
    id: '/admin/plans/',
    path: '/admin/plans/',
    getParentRoute: () => Char123LocaleChar125adminLayoutRouteRoute,
  } as any)
const Char123LocaleChar125adminLayoutAdminFeaturesIndexRoute =
  Char123LocaleChar125adminLayoutAdminFeaturesIndexRouteImport.update({
    id: '/admin/features/',
    path: '/admin/features/',
    getParentRoute: () => Char123LocaleChar125adminLayoutRouteRoute,
  } as any)
const Char123LocaleChar125adminLayoutAdminEmailsIndexRoute =
  Char123LocaleChar125adminLayoutAdminEmailsIndexRouteImport.update({
    id: '/admin/emails/',
    path: '/admin/emails/',
    getParentRoute: () => Char123LocaleChar125adminLayoutRouteRoute,
  } as any)
const Char123LocaleChar125adminLayoutAdminAuditIndexRoute =
  Char123LocaleChar125adminLayoutAdminAuditIndexRouteImport.update({
    id: '/admin/audit/',
    path: '/admin/audit/',
    getParentRoute: () => Char123LocaleChar125adminLayoutRouteRoute,
  } as any)
const Char123LocaleChar125adminLayoutAdminWorkspacesIdIndexRoute =
  Char123LocaleChar125adminLayoutAdminWorkspacesIdIndexRouteImport.update({
    id: '/admin/workspaces/$id/',
    path: '/admin/workspaces/$id/',
    getParentRoute: () => Char123LocaleChar125adminLayoutRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125rootLayoutauthRouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_api/health/live': typeof ApiHealthLiveRoute
  '/{-$locale}/': typeof Char123LocaleChar125rootLayoutIndexRoute
  '/{-$locale}/admin/': typeof Char123LocaleChar125adminLayoutAdminIndexRoute
  '/{-$locale}/app/': typeof Char123LocaleChar125consoleLayoutAppIndexRoute
  '/{-$locale}/about/': typeof Char123LocaleChar125rootLayoutAboutIndexRoute
  '/{-$locale}/changelog/': typeof Char123LocaleChar125rootLayoutChangelogIndexRoute
  '/{-$locale}/error/': typeof Char123LocaleChar125rootLayoutErrorIndexRoute
  '/{-$locale}/playground/': typeof Char123LocaleChar125rootLayoutPlaygroundIndexRoute
  '/{-$locale}/pricing/': typeof Char123LocaleChar125rootLayoutPricingIndexRoute
  '/{-$locale}/privacy-policy/': typeof Char123LocaleChar125rootLayoutPrivacyPolicyIndexRoute
  '/{-$locale}/status/': typeof Char123LocaleChar125rootLayoutStatusIndexRoute
  '/{-$locale}/terms-of-service/': typeof Char123LocaleChar125rootLayoutTermsOfServiceIndexRoute
  '/{-$locale}/admin/audit/': typeof Char123LocaleChar125adminLayoutAdminAuditIndexRoute
  '/{-$locale}/admin/emails/': typeof Char123LocaleChar125adminLayoutAdminEmailsIndexRoute
  '/{-$locale}/admin/features/': typeof Char123LocaleChar125adminLayoutAdminFeaturesIndexRoute
  '/{-$locale}/admin/plans/': typeof Char123LocaleChar125adminLayoutAdminPlansIndexRoute
  '/{-$locale}/admin/settings/': typeof Char123LocaleChar125adminLayoutAdminSettingsIndexRoute
  '/{-$locale}/admin/users/': typeof Char123LocaleChar125adminLayoutAdminUsersIndexRoute
  '/{-$locale}/admin/workspaces/': typeof Char123LocaleChar125adminLayoutAdminWorkspacesIndexRoute
  '/{-$locale}/accept-invite/': typeof Char123LocaleChar125centeredLayoutguestAcceptInviteIndexRoute
  '/{-$locale}/create-an-account/': typeof Char123LocaleChar125centeredLayoutguestCreateAnAccountIndexRoute
  '/{-$locale}/forgot-password/': typeof Char123LocaleChar125centeredLayoutguestForgotPasswordIndexRoute
  '/{-$locale}/reset-password/': typeof Char123LocaleChar125centeredLayoutguestResetPasswordIndexRoute
  '/{-$locale}/sign-in/': typeof Char123LocaleChar125centeredLayoutguestSignInIndexRoute
  '/{-$locale}/app/ai-usage/': typeof Char123LocaleChar125consoleLayoutAppAiUsageIndexRoute
  '/{-$locale}/app/api-keys/': typeof Char123LocaleChar125consoleLayoutAppApiKeysIndexRoute
  '/{-$locale}/app/audit/': typeof Char123LocaleChar125consoleLayoutAppAuditIndexRoute
  '/{-$locale}/app/batch-jobs/': typeof Char123LocaleChar125consoleLayoutAppBatchJobsIndexRoute
  '/{-$locale}/app/billing/': typeof Char123LocaleChar125consoleLayoutAppBillingIndexRoute
  '/{-$locale}/app/features/': typeof Char123LocaleChar125consoleLayoutAppFeaturesIndexRoute
  '/{-$locale}/app/notifications/': typeof Char123LocaleChar125consoleLayoutAppNotificationsIndexRoute
  '/{-$locale}/app/profile/': typeof Char123LocaleChar125consoleLayoutAppProfileIndexRoute
  '/{-$locale}/app/security/': typeof Char123LocaleChar125consoleLayoutAppSecurityIndexRoute
  '/{-$locale}/app/settings/': typeof Char123LocaleChar125consoleLayoutAppSettingsIndexRoute
  '/{-$locale}/app/team/': typeof Char123LocaleChar125consoleLayoutAppTeamIndexRoute
  '/{-$locale}/app/webhooks/': typeof Char123LocaleChar125consoleLayoutAppWebhooksIndexRoute
  '/{-$locale}/dashboard/': typeof Char123LocaleChar125rootLayoutauthDashboardIndexRoute
  '/{-$locale}/onboarding/': typeof Char123LocaleChar125rootLayoutauthOnboardingIndexRoute
  '/{-$locale}/admin/workspaces/$id/': typeof Char123LocaleChar125adminLayoutAdminWorkspacesIdIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}': typeof Char123LocaleChar125rootLayoutIndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_api/health/live': typeof ApiHealthLiveRoute
  '/{-$locale}/admin': typeof Char123LocaleChar125adminLayoutAdminIndexRoute
  '/{-$locale}/app': typeof Char123LocaleChar125consoleLayoutAppIndexRoute
  '/{-$locale}/about': typeof Char123LocaleChar125rootLayoutAboutIndexRoute
  '/{-$locale}/changelog': typeof Char123LocaleChar125rootLayoutChangelogIndexRoute
  '/{-$locale}/error': typeof Char123LocaleChar125rootLayoutErrorIndexRoute
  '/{-$locale}/playground': typeof Char123LocaleChar125rootLayoutPlaygroundIndexRoute
  '/{-$locale}/pricing': typeof Char123LocaleChar125rootLayoutPricingIndexRoute
  '/{-$locale}/privacy-policy': typeof Char123LocaleChar125rootLayoutPrivacyPolicyIndexRoute
  '/{-$locale}/status': typeof Char123LocaleChar125rootLayoutStatusIndexRoute
  '/{-$locale}/terms-of-service': typeof Char123LocaleChar125rootLayoutTermsOfServiceIndexRoute
  '/{-$locale}/admin/audit': typeof Char123LocaleChar125adminLayoutAdminAuditIndexRoute
  '/{-$locale}/admin/emails': typeof Char123LocaleChar125adminLayoutAdminEmailsIndexRoute
  '/{-$locale}/admin/features': typeof Char123LocaleChar125adminLayoutAdminFeaturesIndexRoute
  '/{-$locale}/admin/plans': typeof Char123LocaleChar125adminLayoutAdminPlansIndexRoute
  '/{-$locale}/admin/settings': typeof Char123LocaleChar125adminLayoutAdminSettingsIndexRoute
  '/{-$locale}/admin/users': typeof Char123LocaleChar125adminLayoutAdminUsersIndexRoute
  '/{-$locale}/admin/workspaces': typeof Char123LocaleChar125adminLayoutAdminWorkspacesIndexRoute
  '/{-$locale}/accept-invite': typeof Char123LocaleChar125centeredLayoutguestAcceptInviteIndexRoute
  '/{-$locale}/create-an-account': typeof Char123LocaleChar125centeredLayoutguestCreateAnAccountIndexRoute
  '/{-$locale}/forgot-password': typeof Char123LocaleChar125centeredLayoutguestForgotPasswordIndexRoute
  '/{-$locale}/reset-password': typeof Char123LocaleChar125centeredLayoutguestResetPasswordIndexRoute
  '/{-$locale}/sign-in': typeof Char123LocaleChar125centeredLayoutguestSignInIndexRoute
  '/{-$locale}/app/ai-usage': typeof Char123LocaleChar125consoleLayoutAppAiUsageIndexRoute
  '/{-$locale}/app/api-keys': typeof Char123LocaleChar125consoleLayoutAppApiKeysIndexRoute
  '/{-$locale}/app/audit': typeof Char123LocaleChar125consoleLayoutAppAuditIndexRoute
  '/{-$locale}/app/batch-jobs': typeof Char123LocaleChar125consoleLayoutAppBatchJobsIndexRoute
  '/{-$locale}/app/billing': typeof Char123LocaleChar125consoleLayoutAppBillingIndexRoute
  '/{-$locale}/app/features': typeof Char123LocaleChar125consoleLayoutAppFeaturesIndexRoute
  '/{-$locale}/app/notifications': typeof Char123LocaleChar125consoleLayoutAppNotificationsIndexRoute
  '/{-$locale}/app/profile': typeof Char123LocaleChar125consoleLayoutAppProfileIndexRoute
  '/{-$locale}/app/security': typeof Char123LocaleChar125consoleLayoutAppSecurityIndexRoute
  '/{-$locale}/app/settings': typeof Char123LocaleChar125consoleLayoutAppSettingsIndexRoute
  '/{-$locale}/app/team': typeof Char123LocaleChar125consoleLayoutAppTeamIndexRoute
  '/{-$locale}/app/webhooks': typeof Char123LocaleChar125consoleLayoutAppWebhooksIndexRoute
  '/{-$locale}/dashboard': typeof Char123LocaleChar125rootLayoutauthDashboardIndexRoute
  '/{-$locale}/onboarding': typeof Char123LocaleChar125rootLayoutauthOnboardingIndexRoute
  '/{-$locale}/admin/workspaces/$id': typeof Char123LocaleChar125adminLayoutAdminWorkspacesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/{-$locale}/(admin-layout)': typeof Char123LocaleChar125adminLayoutRouteRouteWithChildren
  '/{-$locale}/(centered-layout)': typeof Char123LocaleChar125centeredLayoutRouteRouteWithChildren
  '/{-$locale}/(console-layout)': typeof Char123LocaleChar125consoleLayoutRouteRouteWithChildren
  '/{-$locale}/(root-layout)': typeof Char123LocaleChar125rootLayoutRouteRouteWithChildren
  '/{-$locale}/(centered-layout)/(guest)': typeof Char123LocaleChar125centeredLayoutguestRouteRouteWithChildren
  '/{-$locale}/(root-layout)/(auth)': typeof Char123LocaleChar125rootLayoutauthRouteRouteWithChildren
  '/_api/health/live': typeof ApiHealthLiveRoute
  '/{-$locale}/(root-layout)/': typeof Char123LocaleChar125rootLayoutIndexRoute
  '/{-$locale}/(admin-layout)/admin/': typeof Char123LocaleChar125adminLayoutAdminIndexRoute
  '/{-$locale}/(console-layout)/app/': typeof Char123LocaleChar125consoleLayoutAppIndexRoute
  '/{-$locale}/(root-layout)/about/': typeof Char123LocaleChar125rootLayoutAboutIndexRoute
  '/{-$locale}/(root-layout)/changelog/': typeof Char123LocaleChar125rootLayoutChangelogIndexRoute
  '/{-$locale}/(root-layout)/error/': typeof Char123LocaleChar125rootLayoutErrorIndexRoute
  '/{-$locale}/(root-layout)/playground/': typeof Char123LocaleChar125rootLayoutPlaygroundIndexRoute
  '/{-$locale}/(root-layout)/pricing/': typeof Char123LocaleChar125rootLayoutPricingIndexRoute
  '/{-$locale}/(root-layout)/privacy-policy/': typeof Char123LocaleChar125rootLayoutPrivacyPolicyIndexRoute
  '/{-$locale}/(root-layout)/status/': typeof Char123LocaleChar125rootLayoutStatusIndexRoute
  '/{-$locale}/(root-layout)/terms-of-service/': typeof Char123LocaleChar125rootLayoutTermsOfServiceIndexRoute
  '/{-$locale}/(admin-layout)/admin/audit/': typeof Char123LocaleChar125adminLayoutAdminAuditIndexRoute
  '/{-$locale}/(admin-layout)/admin/emails/': typeof Char123LocaleChar125adminLayoutAdminEmailsIndexRoute
  '/{-$locale}/(admin-layout)/admin/features/': typeof Char123LocaleChar125adminLayoutAdminFeaturesIndexRoute
  '/{-$locale}/(admin-layout)/admin/plans/': typeof Char123LocaleChar125adminLayoutAdminPlansIndexRoute
  '/{-$locale}/(admin-layout)/admin/settings/': typeof Char123LocaleChar125adminLayoutAdminSettingsIndexRoute
  '/{-$locale}/(admin-layout)/admin/users/': typeof Char123LocaleChar125adminLayoutAdminUsersIndexRoute
  '/{-$locale}/(admin-layout)/admin/workspaces/': typeof Char123LocaleChar125adminLayoutAdminWorkspacesIndexRoute
  '/{-$locale}/(centered-layout)/(guest)/accept-invite/': typeof Char123LocaleChar125centeredLayoutguestAcceptInviteIndexRoute
  '/{-$locale}/(centered-layout)/(guest)/create-an-account/': typeof Char123LocaleChar125centeredLayoutguestCreateAnAccountIndexRoute
  '/{-$locale}/(centered-layout)/(guest)/forgot-password/': typeof Char123LocaleChar125centeredLayoutguestForgotPasswordIndexRoute
  '/{-$locale}/(centered-layout)/(guest)/reset-password/': typeof Char123LocaleChar125centeredLayoutguestResetPasswordIndexRoute
  '/{-$locale}/(centered-layout)/(guest)/sign-in/': typeof Char123LocaleChar125centeredLayoutguestSignInIndexRoute
  '/{-$locale}/(console-layout)/app/ai-usage/': typeof Char123LocaleChar125consoleLayoutAppAiUsageIndexRoute
  '/{-$locale}/(console-layout)/app/api-keys/': typeof Char123LocaleChar125consoleLayoutAppApiKeysIndexRoute
  '/{-$locale}/(console-layout)/app/audit/': typeof Char123LocaleChar125consoleLayoutAppAuditIndexRoute
  '/{-$locale}/(console-layout)/app/batch-jobs/': typeof Char123LocaleChar125consoleLayoutAppBatchJobsIndexRoute
  '/{-$locale}/(console-layout)/app/billing/': typeof Char123LocaleChar125consoleLayoutAppBillingIndexRoute
  '/{-$locale}/(console-layout)/app/features/': typeof Char123LocaleChar125consoleLayoutAppFeaturesIndexRoute
  '/{-$locale}/(console-layout)/app/notifications/': typeof Char123LocaleChar125consoleLayoutAppNotificationsIndexRoute
  '/{-$locale}/(console-layout)/app/profile/': typeof Char123LocaleChar125consoleLayoutAppProfileIndexRoute
  '/{-$locale}/(console-layout)/app/security/': typeof Char123LocaleChar125consoleLayoutAppSecurityIndexRoute
  '/{-$locale}/(console-layout)/app/settings/': typeof Char123LocaleChar125consoleLayoutAppSettingsIndexRoute
  '/{-$locale}/(console-layout)/app/team/': typeof Char123LocaleChar125consoleLayoutAppTeamIndexRoute
  '/{-$locale}/(console-layout)/app/webhooks/': typeof Char123LocaleChar125consoleLayoutAppWebhooksIndexRoute
  '/{-$locale}/(root-layout)/(auth)/dashboard/': typeof Char123LocaleChar125rootLayoutauthDashboardIndexRoute
  '/{-$locale}/(root-layout)/(auth)/onboarding/': typeof Char123LocaleChar125rootLayoutauthOnboardingIndexRoute
  '/{-$locale}/(admin-layout)/admin/workspaces/$id/': typeof Char123LocaleChar125adminLayoutAdminWorkspacesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_api/health/live'
    | '/{-$locale}/'
    | '/{-$locale}/admin/'
    | '/{-$locale}/app/'
    | '/{-$locale}/about/'
    | '/{-$locale}/changelog/'
    | '/{-$locale}/error/'
    | '/{-$locale}/playground/'
    | '/{-$locale}/pricing/'
    | '/{-$locale}/privacy-policy/'
    | '/{-$locale}/status/'
    | '/{-$locale}/terms-of-service/'
    | '/{-$locale}/admin/audit/'
    | '/{-$locale}/admin/emails/'
    | '/{-$locale}/admin/features/'
    | '/{-$locale}/admin/plans/'
    | '/{-$locale}/admin/settings/'
    | '/{-$locale}/admin/users/'
    | '/{-$locale}/admin/workspaces/'
    | '/{-$locale}/accept-invite/'
    | '/{-$locale}/create-an-account/'
    | '/{-$locale}/forgot-password/'
    | '/{-$locale}/reset-password/'
    | '/{-$locale}/sign-in/'
    | '/{-$locale}/app/ai-usage/'
    | '/{-$locale}/app/api-keys/'
    | '/{-$locale}/app/audit/'
    | '/{-$locale}/app/batch-jobs/'
    | '/{-$locale}/app/billing/'
    | '/{-$locale}/app/features/'
    | '/{-$locale}/app/notifications/'
    | '/{-$locale}/app/profile/'
    | '/{-$locale}/app/security/'
    | '/{-$locale}/app/settings/'
    | '/{-$locale}/app/team/'
    | '/{-$locale}/app/webhooks/'
    | '/{-$locale}/dashboard/'
    | '/{-$locale}/onboarding/'
    | '/{-$locale}/admin/workspaces/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_api/health/live'
    | '/{-$locale}/admin'
    | '/{-$locale}/app'
    | '/{-$locale}/about'
    | '/{-$locale}/changelog'
    | '/{-$locale}/error'
    | '/{-$locale}/playground'
    | '/{-$locale}/pricing'
    | '/{-$locale}/privacy-policy'
    | '/{-$locale}/status'
    | '/{-$locale}/terms-of-service'
    | '/{-$locale}/admin/audit'
    | '/{-$locale}/admin/emails'
    | '/{-$locale}/admin/features'
    | '/{-$locale}/admin/plans'
    | '/{-$locale}/admin/settings'
    | '/{-$locale}/admin/users'
    | '/{-$locale}/admin/workspaces'
    | '/{-$locale}/accept-invite'
    | '/{-$locale}/create-an-account'
    | '/{-$locale}/forgot-password'
    | '/{-$locale}/reset-password'
    | '/{-$locale}/sign-in'
    | '/{-$locale}/app/ai-usage'
    | '/{-$locale}/app/api-keys'
    | '/{-$locale}/app/audit'
    | '/{-$locale}/app/batch-jobs'
    | '/{-$locale}/app/billing'
    | '/{-$locale}/app/features'
    | '/{-$locale}/app/notifications'
    | '/{-$locale}/app/profile'
    | '/{-$locale}/app/security'
    | '/{-$locale}/app/settings'
    | '/{-$locale}/app/team'
    | '/{-$locale}/app/webhooks'
    | '/{-$locale}/dashboard'
    | '/{-$locale}/onboarding'
    | '/{-$locale}/admin/workspaces/$id'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/{-$locale}/(admin-layout)'
    | '/{-$locale}/(centered-layout)'
    | '/{-$locale}/(console-layout)'
    | '/{-$locale}/(root-layout)'
    | '/{-$locale}/(centered-layout)/(guest)'
    | '/{-$locale}/(root-layout)/(auth)'
    | '/_api/health/live'
    | '/{-$locale}/(root-layout)/'
    | '/{-$locale}/(admin-layout)/admin/'
    | '/{-$locale}/(console-layout)/app/'
    | '/{-$locale}/(root-layout)/about/'
    | '/{-$locale}/(root-layout)/changelog/'
    | '/{-$locale}/(root-layout)/error/'
    | '/{-$locale}/(root-layout)/playground/'
    | '/{-$locale}/(root-layout)/pricing/'
    | '/{-$locale}/(root-layout)/privacy-policy/'
    | '/{-$locale}/(root-layout)/status/'
    | '/{-$locale}/(root-layout)/terms-of-service/'
    | '/{-$locale}/(admin-layout)/admin/audit/'
    | '/{-$locale}/(admin-layout)/admin/emails/'
    | '/{-$locale}/(admin-layout)/admin/features/'
    | '/{-$locale}/(admin-layout)/admin/plans/'
    | '/{-$locale}/(admin-layout)/admin/settings/'
    | '/{-$locale}/(admin-layout)/admin/users/'
    | '/{-$locale}/(admin-layout)/admin/workspaces/'
    | '/{-$locale}/(centered-layout)/(guest)/accept-invite/'
    | '/{-$locale}/(centered-layout)/(guest)/create-an-account/'
    | '/{-$locale}/(centered-layout)/(guest)/forgot-password/'
    | '/{-$locale}/(centered-layout)/(guest)/reset-password/'
    | '/{-$locale}/(centered-layout)/(guest)/sign-in/'
    | '/{-$locale}/(console-layout)/app/ai-usage/'
    | '/{-$locale}/(console-layout)/app/api-keys/'
    | '/{-$locale}/(console-layout)/app/audit/'
    | '/{-$locale}/(console-layout)/app/batch-jobs/'
    | '/{-$locale}/(console-layout)/app/billing/'
    | '/{-$locale}/(console-layout)/app/features/'
    | '/{-$locale}/(console-layout)/app/notifications/'
    | '/{-$locale}/(console-layout)/app/profile/'
    | '/{-$locale}/(console-layout)/app/security/'
    | '/{-$locale}/(console-layout)/app/settings/'
    | '/{-$locale}/(console-layout)/app/team/'
    | '/{-$locale}/(console-layout)/app/webhooks/'
    | '/{-$locale}/(root-layout)/(auth)/dashboard/'
    | '/{-$locale}/(root-layout)/(auth)/onboarding/'
    | '/{-$locale}/(admin-layout)/admin/workspaces/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125RouteRoute: typeof Char123LocaleChar125RouteRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiHealthLiveRoute: typeof ApiHealthLiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/(root-layout)': {
      id: '/{-$locale}/(root-layout)'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(console-layout)': {
      id: '/{-$locale}/(console-layout)'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125consoleLayoutRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(centered-layout)': {
      id: '/{-$locale}/(centered-layout)'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125centeredLayoutRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(admin-layout)': {
      id: '/{-$locale}/(admin-layout)'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125adminLayoutRouteRouteImport
      parentRoute: typeof Char123LocaleChar125RouteRoute
    }
    '/{-$locale}/(root-layout)/': {
      id: '/{-$locale}/(root-layout)/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutRouteRoute
    }
    '/_api/health/live': {
      id: '/_api/health/live'
      path: '/_api/health/live'
      fullPath: '/_api/health/live'
      preLoaderRoute: typeof ApiHealthLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/(root-layout)/(auth)': {
      id: '/{-$locale}/(root-layout)/(auth)'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutauthRouteRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutRouteRoute
    }
    '/{-$locale}/(centered-layout)/(guest)': {
      id: '/{-$locale}/(centered-layout)/(guest)'
      path: ''
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125centeredLayoutguestRouteRouteImport
      parentRoute: typeof Char123LocaleChar125centeredLayoutRouteRoute
    }
    '/{-$locale}/(root-layout)/terms-of-service/': {
      id: '/{-$locale}/(root-layout)/terms-of-service/'
      path: '/terms-of-service'
      fullPath: '/{-$locale}/terms-of-service/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutTermsOfServiceIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutRouteRoute
    }
    '/{-$locale}/(root-layout)/status/': {
      id: '/{-$locale}/(root-layout)/status/'
      path: '/status'
      fullPath: '/{-$locale}/status/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutStatusIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutRouteRoute
    }
    '/{-$locale}/(root-layout)/privacy-policy/': {
      id: '/{-$locale}/(root-layout)/privacy-policy/'
      path: '/privacy-policy'
      fullPath: '/{-$locale}/privacy-policy/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutPrivacyPolicyIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutRouteRoute
    }
    '/{-$locale}/(root-layout)/pricing/': {
      id: '/{-$locale}/(root-layout)/pricing/'
      path: '/pricing'
      fullPath: '/{-$locale}/pricing/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutPricingIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutRouteRoute
    }
    '/{-$locale}/(root-layout)/playground/': {
      id: '/{-$locale}/(root-layout)/playground/'
      path: '/playground'
      fullPath: '/{-$locale}/playground/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutPlaygroundIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutRouteRoute
    }
    '/{-$locale}/(root-layout)/error/': {
      id: '/{-$locale}/(root-layout)/error/'
      path: '/error'
      fullPath: '/{-$locale}/error/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutErrorIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutRouteRoute
    }
    '/{-$locale}/(root-layout)/changelog/': {
      id: '/{-$locale}/(root-layout)/changelog/'
      path: '/changelog'
      fullPath: '/{-$locale}/changelog/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutChangelogIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutRouteRoute
    }
    '/{-$locale}/(root-layout)/about/': {
      id: '/{-$locale}/(root-layout)/about/'
      path: '/about'
      fullPath: '/{-$locale}/about/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutAboutIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutRouteRoute
    }
    '/{-$locale}/(console-layout)/app/': {
      id: '/{-$locale}/(console-layout)/app/'
      path: '/app'
      fullPath: '/{-$locale}/app/'
      preLoaderRoute: typeof Char123LocaleChar125consoleLayoutAppIndexRouteImport
      parentRoute: typeof Char123LocaleChar125consoleLayoutRouteRoute
    }
    '/{-$locale}/(admin-layout)/admin/': {
      id: '/{-$locale}/(admin-layout)/admin/'
      path: '/admin'
      fullPath: '/{-$locale}/admin/'
      preLoaderRoute: typeof Char123LocaleChar125adminLayoutAdminIndexRouteImport
      parentRoute: typeof Char123LocaleChar125adminLayoutRouteRoute
    }
    '/{-$locale}/(root-layout)/(auth)/onboarding/': {
      id: '/{-$locale}/(root-layout)/(auth)/onboarding/'
      path: '/onboarding'
      fullPath: '/{-$locale}/onboarding/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutauthOnboardingIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutauthRouteRoute
    }
    '/{-$locale}/(root-layout)/(auth)/dashboard/': {
      id: '/{-$locale}/(root-layout)/(auth)/dashboard/'
      path: '/dashboard'
      fullPath: '/{-$locale}/dashboard/'
      preLoaderRoute: typeof Char123LocaleChar125rootLayoutauthDashboardIndexRouteImport
      parentRoute: typeof Char123LocaleChar125rootLayoutauthRouteRoute
    }
    '/{-$locale}/(console-layout)/app/webhooks/': {
      id: '/{-$locale}/(console-layout)/app/webhooks/'
      path: '/app/webhooks'
      fullPath: '/{-$locale}/app/webhooks/'
      preLoaderRoute: typeof Char123LocaleChar125consoleLayoutAppWebhooksIndexRouteImport
      parentRoute: typeof Char123LocaleChar125consoleLayoutRouteRoute
    }
    '/{-$locale}/(console-layout)/app/team/': {
      id: '/{-$locale}/(console-layout)/app/team/'
      path: '/app/team'
      fullPath: '/{-$locale}/app/team/'
      preLoaderRoute: typeof Char123LocaleChar125consoleLayoutAppTeamIndexRouteImport
      parentRoute: typeof Char123LocaleChar125consoleLayoutRouteRoute
    }
    '/{-$locale}/(console-layout)/app/settings/': {
      id: '/{-$locale}/(console-layout)/app/settings/'
      path: '/app/settings'
      fullPath: '/{-$locale}/app/settings/'
      preLoaderRoute: typeof Char123LocaleChar125consoleLayoutAppSettingsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125consoleLayoutRouteRoute
    }
    '/{-$locale}/(console-layout)/app/security/': {
      id: '/{-$locale}/(console-layout)/app/security/'
      path: '/app/security'
      fullPath: '/{-$locale}/app/security/'
      preLoaderRoute: typeof Char123LocaleChar125consoleLayoutAppSecurityIndexRouteImport
      parentRoute: typeof Char123LocaleChar125consoleLayoutRouteRoute
    }
    '/{-$locale}/(console-layout)/app/profile/': {
      id: '/{-$locale}/(console-layout)/app/profile/'
      path: '/app/profile'
      fullPath: '/{-$locale}/app/profile/'
      preLoaderRoute: typeof Char123LocaleChar125consoleLayoutAppProfileIndexRouteImport
      parentRoute: typeof Char123LocaleChar125consoleLayoutRouteRoute
    }
    '/{-$locale}/(console-layout)/app/notifications/': {
      id: '/{-$locale}/(console-layout)/app/notifications/'
      path: '/app/notifications'
      fullPath: '/{-$locale}/app/notifications/'
      preLoaderRoute: typeof Char123LocaleChar125consoleLayoutAppNotificationsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125consoleLayoutRouteRoute
    }
    '/{-$locale}/(console-layout)/app/features/': {
      id: '/{-$locale}/(console-layout)/app/features/'
      path: '/app/features'
      fullPath: '/{-$locale}/app/features/'
      preLoaderRoute: typeof Char123LocaleChar125consoleLayoutAppFeaturesIndexRouteImport
      parentRoute: typeof Char123LocaleChar125consoleLayoutRouteRoute
    }
    '/{-$locale}/(console-layout)/app/billing/': {
      id: '/{-$locale}/(console-layout)/app/billing/'
      path: '/app/billing'
      fullPath: '/{-$locale}/app/billing/'
      preLoaderRoute: typeof Char123LocaleChar125consoleLayoutAppBillingIndexRouteImport
      parentRoute: typeof Char123LocaleChar125consoleLayoutRouteRoute
    }
    '/{-$locale}/(console-layout)/app/batch-jobs/': {
      id: '/{-$locale}/(console-layout)/app/batch-jobs/'
      path: '/app/batch-jobs'
      fullPath: '/{-$locale}/app/batch-jobs/'
      preLoaderRoute: typeof Char123LocaleChar125consoleLayoutAppBatchJobsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125consoleLayoutRouteRoute
    }
    '/{-$locale}/(console-layout)/app/audit/': {
      id: '/{-$locale}/(console-layout)/app/audit/'
      path: '/app/audit'
      fullPath: '/{-$locale}/app/audit/'
      preLoaderRoute: typeof Char123LocaleChar125consoleLayoutAppAuditIndexRouteImport
      parentRoute: typeof Char123LocaleChar125consoleLayoutRouteRoute
    }
    '/{-$locale}/(console-layout)/app/api-keys/': {
      id: '/{-$locale}/(console-layout)/app/api-keys/'
      path: '/app/api-keys'
      fullPath: '/{-$locale}/app/api-keys/'
      preLoaderRoute: typeof Char123LocaleChar125consoleLayoutAppApiKeysIndexRouteImport
      parentRoute: typeof Char123LocaleChar125consoleLayoutRouteRoute
    }
    '/{-$locale}/(console-layout)/app/ai-usage/': {
      id: '/{-$locale}/(console-layout)/app/ai-usage/'
      path: '/app/ai-usage'
      fullPath: '/{-$locale}/app/ai-usage/'
      preLoaderRoute: typeof Char123LocaleChar125consoleLayoutAppAiUsageIndexRouteImport
      parentRoute: typeof Char123LocaleChar125consoleLayoutRouteRoute
    }
    '/{-$locale}/(centered-layout)/(guest)/sign-in/': {
      id: '/{-$locale}/(centered-layout)/(guest)/sign-in/'
      path: '/sign-in'
      fullPath: '/{-$locale}/sign-in/'
      preLoaderRoute: typeof Char123LocaleChar125centeredLayoutguestSignInIndexRouteImport
      parentRoute: typeof Char123LocaleChar125centeredLayoutguestRouteRoute
    }
    '/{-$locale}/(centered-layout)/(guest)/reset-password/': {
      id: '/{-$locale}/(centered-layout)/(guest)/reset-password/'
      path: '/reset-password'
      fullPath: '/{-$locale}/reset-password/'
      preLoaderRoute: typeof Char123LocaleChar125centeredLayoutguestResetPasswordIndexRouteImport
      parentRoute: typeof Char123LocaleChar125centeredLayoutguestRouteRoute
    }
    '/{-$locale}/(centered-layout)/(guest)/forgot-password/': {
      id: '/{-$locale}/(centered-layout)/(guest)/forgot-password/'
      path: '/forgot-password'
      fullPath: '/{-$locale}/forgot-password/'
      preLoaderRoute: typeof Char123LocaleChar125centeredLayoutguestForgotPasswordIndexRouteImport
      parentRoute: typeof Char123LocaleChar125centeredLayoutguestRouteRoute
    }
    '/{-$locale}/(centered-layout)/(guest)/create-an-account/': {
      id: '/{-$locale}/(centered-layout)/(guest)/create-an-account/'
      path: '/create-an-account'
      fullPath: '/{-$locale}/create-an-account/'
      preLoaderRoute: typeof Char123LocaleChar125centeredLayoutguestCreateAnAccountIndexRouteImport
      parentRoute: typeof Char123LocaleChar125centeredLayoutguestRouteRoute
    }
    '/{-$locale}/(centered-layout)/(guest)/accept-invite/': {
      id: '/{-$locale}/(centered-layout)/(guest)/accept-invite/'
      path: '/accept-invite'
      fullPath: '/{-$locale}/accept-invite/'
      preLoaderRoute: typeof Char123LocaleChar125centeredLayoutguestAcceptInviteIndexRouteImport
      parentRoute: typeof Char123LocaleChar125centeredLayoutguestRouteRoute
    }
    '/{-$locale}/(admin-layout)/admin/workspaces/': {
      id: '/{-$locale}/(admin-layout)/admin/workspaces/'
      path: '/admin/workspaces'
      fullPath: '/{-$locale}/admin/workspaces/'
      preLoaderRoute: typeof Char123LocaleChar125adminLayoutAdminWorkspacesIndexRouteImport
      parentRoute: typeof Char123LocaleChar125adminLayoutRouteRoute
    }
    '/{-$locale}/(admin-layout)/admin/users/': {
      id: '/{-$locale}/(admin-layout)/admin/users/'
      path: '/admin/users'
      fullPath: '/{-$locale}/admin/users/'
      preLoaderRoute: typeof Char123LocaleChar125adminLayoutAdminUsersIndexRouteImport
      parentRoute: typeof Char123LocaleChar125adminLayoutRouteRoute
    }
    '/{-$locale}/(admin-layout)/admin/settings/': {
      id: '/{-$locale}/(admin-layout)/admin/settings/'
      path: '/admin/settings'
      fullPath: '/{-$locale}/admin/settings/'
      preLoaderRoute: typeof Char123LocaleChar125adminLayoutAdminSettingsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125adminLayoutRouteRoute
    }
    '/{-$locale}/(admin-layout)/admin/plans/': {
      id: '/{-$locale}/(admin-layout)/admin/plans/'
      path: '/admin/plans'
      fullPath: '/{-$locale}/admin/plans/'
      preLoaderRoute: typeof Char123LocaleChar125adminLayoutAdminPlansIndexRouteImport
      parentRoute: typeof Char123LocaleChar125adminLayoutRouteRoute
    }
    '/{-$locale}/(admin-layout)/admin/features/': {
      id: '/{-$locale}/(admin-layout)/admin/features/'
      path: '/admin/features'
      fullPath: '/{-$locale}/admin/features/'
      preLoaderRoute: typeof Char123LocaleChar125adminLayoutAdminFeaturesIndexRouteImport
      parentRoute: typeof Char123LocaleChar125adminLayoutRouteRoute
    }
    '/{-$locale}/(admin-layout)/admin/emails/': {
      id: '/{-$locale}/(admin-layout)/admin/emails/'
      path: '/admin/emails'
      fullPath: '/{-$locale}/admin/emails/'
      preLoaderRoute: typeof Char123LocaleChar125adminLayoutAdminEmailsIndexRouteImport
      parentRoute: typeof Char123LocaleChar125adminLayoutRouteRoute
    }
    '/{-$locale}/(admin-layout)/admin/audit/': {
      id: '/{-$locale}/(admin-layout)/admin/audit/'
      path: '/admin/audit'
      fullPath: '/{-$locale}/admin/audit/'
      preLoaderRoute: typeof Char123LocaleChar125adminLayoutAdminAuditIndexRouteImport
      parentRoute: typeof Char123LocaleChar125adminLayoutRouteRoute
    }
    '/{-$locale}/(admin-layout)/admin/workspaces/$id/': {
      id: '/{-$locale}/(admin-layout)/admin/workspaces/$id/'
      path: '/admin/workspaces/$id'
      fullPath: '/{-$locale}/admin/workspaces/$id/'
      preLoaderRoute: typeof Char123LocaleChar125adminLayoutAdminWorkspacesIdIndexRouteImport
      parentRoute: typeof Char123LocaleChar125adminLayoutRouteRoute
    }
  }
}

interface Char123LocaleChar125adminLayoutRouteRouteChildren {
  Char123LocaleChar125adminLayoutAdminIndexRoute: typeof Char123LocaleChar125adminLayoutAdminIndexRoute
  Char123LocaleChar125adminLayoutAdminAuditIndexRoute: typeof Char123LocaleChar125adminLayoutAdminAuditIndexRoute
  Char123LocaleChar125adminLayoutAdminEmailsIndexRoute: typeof Char123LocaleChar125adminLayoutAdminEmailsIndexRoute
  Char123LocaleChar125adminLayoutAdminFeaturesIndexRoute: typeof Char123LocaleChar125adminLayoutAdminFeaturesIndexRoute
  Char123LocaleChar125adminLayoutAdminPlansIndexRoute: typeof Char123LocaleChar125adminLayoutAdminPlansIndexRoute
  Char123LocaleChar125adminLayoutAdminSettingsIndexRoute: typeof Char123LocaleChar125adminLayoutAdminSettingsIndexRoute
  Char123LocaleChar125adminLayoutAdminUsersIndexRoute: typeof Char123LocaleChar125adminLayoutAdminUsersIndexRoute
  Char123LocaleChar125adminLayoutAdminWorkspacesIndexRoute: typeof Char123LocaleChar125adminLayoutAdminWorkspacesIndexRoute
  Char123LocaleChar125adminLayoutAdminWorkspacesIdIndexRoute: typeof Char123LocaleChar125adminLayoutAdminWorkspacesIdIndexRoute
}

const Char123LocaleChar125adminLayoutRouteRouteChildren: Char123LocaleChar125adminLayoutRouteRouteChildren =
  {
    Char123LocaleChar125adminLayoutAdminIndexRoute:
      Char123LocaleChar125adminLayoutAdminIndexRoute,
    Char123LocaleChar125adminLayoutAdminAuditIndexRoute:
      Char123LocaleChar125adminLayoutAdminAuditIndexRoute,
    Char123LocaleChar125adminLayoutAdminEmailsIndexRoute:
      Char123LocaleChar125adminLayoutAdminEmailsIndexRoute,
    Char123LocaleChar125adminLayoutAdminFeaturesIndexRoute:
      Char123LocaleChar125adminLayoutAdminFeaturesIndexRoute,
    Char123LocaleChar125adminLayoutAdminPlansIndexRoute:
      Char123LocaleChar125adminLayoutAdminPlansIndexRoute,
    Char123LocaleChar125adminLayoutAdminSettingsIndexRoute:
      Char123LocaleChar125adminLayoutAdminSettingsIndexRoute,
    Char123LocaleChar125adminLayoutAdminUsersIndexRoute:
      Char123LocaleChar125adminLayoutAdminUsersIndexRoute,
    Char123LocaleChar125adminLayoutAdminWorkspacesIndexRoute:
      Char123LocaleChar125adminLayoutAdminWorkspacesIndexRoute,
    Char123LocaleChar125adminLayoutAdminWorkspacesIdIndexRoute:
      Char123LocaleChar125adminLayoutAdminWorkspacesIdIndexRoute,
  }

const Char123LocaleChar125adminLayoutRouteRouteWithChildren =
  Char123LocaleChar125adminLayoutRouteRoute._addFileChildren(
    Char123LocaleChar125adminLayoutRouteRouteChildren,
  )

interface Char123LocaleChar125centeredLayoutguestRouteRouteChildren {
  Char123LocaleChar125centeredLayoutguestAcceptInviteIndexRoute: typeof Char123LocaleChar125centeredLayoutguestAcceptInviteIndexRoute
  Char123LocaleChar125centeredLayoutguestCreateAnAccountIndexRoute: typeof Char123LocaleChar125centeredLayoutguestCreateAnAccountIndexRoute
  Char123LocaleChar125centeredLayoutguestForgotPasswordIndexRoute: typeof Char123LocaleChar125centeredLayoutguestForgotPasswordIndexRoute
  Char123LocaleChar125centeredLayoutguestResetPasswordIndexRoute: typeof Char123LocaleChar125centeredLayoutguestResetPasswordIndexRoute
  Char123LocaleChar125centeredLayoutguestSignInIndexRoute: typeof Char123LocaleChar125centeredLayoutguestSignInIndexRoute
}

const Char123LocaleChar125centeredLayoutguestRouteRouteChildren: Char123LocaleChar125centeredLayoutguestRouteRouteChildren =
  {
    Char123LocaleChar125centeredLayoutguestAcceptInviteIndexRoute:
      Char123LocaleChar125centeredLayoutguestAcceptInviteIndexRoute,
    Char123LocaleChar125centeredLayoutguestCreateAnAccountIndexRoute:
      Char123LocaleChar125centeredLayoutguestCreateAnAccountIndexRoute,
    Char123LocaleChar125centeredLayoutguestForgotPasswordIndexRoute:
      Char123LocaleChar125centeredLayoutguestForgotPasswordIndexRoute,
    Char123LocaleChar125centeredLayoutguestResetPasswordIndexRoute:
      Char123LocaleChar125centeredLayoutguestResetPasswordIndexRoute,
    Char123LocaleChar125centeredLayoutguestSignInIndexRoute:
      Char123LocaleChar125centeredLayoutguestSignInIndexRoute,
  }

const Char123LocaleChar125centeredLayoutguestRouteRouteWithChildren =
  Char123LocaleChar125centeredLayoutguestRouteRoute._addFileChildren(
    Char123LocaleChar125centeredLayoutguestRouteRouteChildren,
  )

interface Char123LocaleChar125centeredLayoutRouteRouteChildren {
  Char123LocaleChar125centeredLayoutguestRouteRoute: typeof Char123LocaleChar125centeredLayoutguestRouteRouteWithChildren
}

const Char123LocaleChar125centeredLayoutRouteRouteChildren: Char123LocaleChar125centeredLayoutRouteRouteChildren =
  {
    Char123LocaleChar125centeredLayoutguestRouteRoute:
      Char123LocaleChar125centeredLayoutguestRouteRouteWithChildren,
  }

const Char123LocaleChar125centeredLayoutRouteRouteWithChildren =
  Char123LocaleChar125centeredLayoutRouteRoute._addFileChildren(
    Char123LocaleChar125centeredLayoutRouteRouteChildren,
  )

interface Char123LocaleChar125consoleLayoutRouteRouteChildren {
  Char123LocaleChar125consoleLayoutAppIndexRoute: typeof Char123LocaleChar125consoleLayoutAppIndexRoute
  Char123LocaleChar125consoleLayoutAppAiUsageIndexRoute: typeof Char123LocaleChar125consoleLayoutAppAiUsageIndexRoute
  Char123LocaleChar125consoleLayoutAppApiKeysIndexRoute: typeof Char123LocaleChar125consoleLayoutAppApiKeysIndexRoute
  Char123LocaleChar125consoleLayoutAppAuditIndexRoute: typeof Char123LocaleChar125consoleLayoutAppAuditIndexRoute
  Char123LocaleChar125consoleLayoutAppBatchJobsIndexRoute: typeof Char123LocaleChar125consoleLayoutAppBatchJobsIndexRoute
  Char123LocaleChar125consoleLayoutAppBillingIndexRoute: typeof Char123LocaleChar125consoleLayoutAppBillingIndexRoute
  Char123LocaleChar125consoleLayoutAppFeaturesIndexRoute: typeof Char123LocaleChar125consoleLayoutAppFeaturesIndexRoute
  Char123LocaleChar125consoleLayoutAppNotificationsIndexRoute: typeof Char123LocaleChar125consoleLayoutAppNotificationsIndexRoute
  Char123LocaleChar125consoleLayoutAppProfileIndexRoute: typeof Char123LocaleChar125consoleLayoutAppProfileIndexRoute
  Char123LocaleChar125consoleLayoutAppSecurityIndexRoute: typeof Char123LocaleChar125consoleLayoutAppSecurityIndexRoute
  Char123LocaleChar125consoleLayoutAppSettingsIndexRoute: typeof Char123LocaleChar125consoleLayoutAppSettingsIndexRoute
  Char123LocaleChar125consoleLayoutAppTeamIndexRoute: typeof Char123LocaleChar125consoleLayoutAppTeamIndexRoute
  Char123LocaleChar125consoleLayoutAppWebhooksIndexRoute: typeof Char123LocaleChar125consoleLayoutAppWebhooksIndexRoute
}

const Char123LocaleChar125consoleLayoutRouteRouteChildren: Char123LocaleChar125consoleLayoutRouteRouteChildren =
  {
    Char123LocaleChar125consoleLayoutAppIndexRoute:
      Char123LocaleChar125consoleLayoutAppIndexRoute,
    Char123LocaleChar125consoleLayoutAppAiUsageIndexRoute:
      Char123LocaleChar125consoleLayoutAppAiUsageIndexRoute,
    Char123LocaleChar125consoleLayoutAppApiKeysIndexRoute:
      Char123LocaleChar125consoleLayoutAppApiKeysIndexRoute,
    Char123LocaleChar125consoleLayoutAppAuditIndexRoute:
      Char123LocaleChar125consoleLayoutAppAuditIndexRoute,
    Char123LocaleChar125consoleLayoutAppBatchJobsIndexRoute:
      Char123LocaleChar125consoleLayoutAppBatchJobsIndexRoute,
    Char123LocaleChar125consoleLayoutAppBillingIndexRoute:
      Char123LocaleChar125consoleLayoutAppBillingIndexRoute,
    Char123LocaleChar125consoleLayoutAppFeaturesIndexRoute:
      Char123LocaleChar125consoleLayoutAppFeaturesIndexRoute,
    Char123LocaleChar125consoleLayoutAppNotificationsIndexRoute:
      Char123LocaleChar125consoleLayoutAppNotificationsIndexRoute,
    Char123LocaleChar125consoleLayoutAppProfileIndexRoute:
      Char123LocaleChar125consoleLayoutAppProfileIndexRoute,
    Char123LocaleChar125consoleLayoutAppSecurityIndexRoute:
      Char123LocaleChar125consoleLayoutAppSecurityIndexRoute,
    Char123LocaleChar125consoleLayoutAppSettingsIndexRoute:
      Char123LocaleChar125consoleLayoutAppSettingsIndexRoute,
    Char123LocaleChar125consoleLayoutAppTeamIndexRoute:
      Char123LocaleChar125consoleLayoutAppTeamIndexRoute,
    Char123LocaleChar125consoleLayoutAppWebhooksIndexRoute:
      Char123LocaleChar125consoleLayoutAppWebhooksIndexRoute,
  }

const Char123LocaleChar125consoleLayoutRouteRouteWithChildren =
  Char123LocaleChar125consoleLayoutRouteRoute._addFileChildren(
    Char123LocaleChar125consoleLayoutRouteRouteChildren,
  )

interface Char123LocaleChar125rootLayoutauthRouteRouteChildren {
  Char123LocaleChar125rootLayoutauthDashboardIndexRoute: typeof Char123LocaleChar125rootLayoutauthDashboardIndexRoute
  Char123LocaleChar125rootLayoutauthOnboardingIndexRoute: typeof Char123LocaleChar125rootLayoutauthOnboardingIndexRoute
}

const Char123LocaleChar125rootLayoutauthRouteRouteChildren: Char123LocaleChar125rootLayoutauthRouteRouteChildren =
  {
    Char123LocaleChar125rootLayoutauthDashboardIndexRoute:
      Char123LocaleChar125rootLayoutauthDashboardIndexRoute,
    Char123LocaleChar125rootLayoutauthOnboardingIndexRoute:
      Char123LocaleChar125rootLayoutauthOnboardingIndexRoute,
  }

const Char123LocaleChar125rootLayoutauthRouteRouteWithChildren =
  Char123LocaleChar125rootLayoutauthRouteRoute._addFileChildren(
    Char123LocaleChar125rootLayoutauthRouteRouteChildren,
  )

interface Char123LocaleChar125rootLayoutRouteRouteChildren {
  Char123LocaleChar125rootLayoutauthRouteRoute: typeof Char123LocaleChar125rootLayoutauthRouteRouteWithChildren
  Char123LocaleChar125rootLayoutIndexRoute: typeof Char123LocaleChar125rootLayoutIndexRoute
  Char123LocaleChar125rootLayoutAboutIndexRoute: typeof Char123LocaleChar125rootLayoutAboutIndexRoute
  Char123LocaleChar125rootLayoutChangelogIndexRoute: typeof Char123LocaleChar125rootLayoutChangelogIndexRoute
  Char123LocaleChar125rootLayoutErrorIndexRoute: typeof Char123LocaleChar125rootLayoutErrorIndexRoute
  Char123LocaleChar125rootLayoutPlaygroundIndexRoute: typeof Char123LocaleChar125rootLayoutPlaygroundIndexRoute
  Char123LocaleChar125rootLayoutPricingIndexRoute: typeof Char123LocaleChar125rootLayoutPricingIndexRoute
  Char123LocaleChar125rootLayoutPrivacyPolicyIndexRoute: typeof Char123LocaleChar125rootLayoutPrivacyPolicyIndexRoute
  Char123LocaleChar125rootLayoutStatusIndexRoute: typeof Char123LocaleChar125rootLayoutStatusIndexRoute
  Char123LocaleChar125rootLayoutTermsOfServiceIndexRoute: typeof Char123LocaleChar125rootLayoutTermsOfServiceIndexRoute
}

const Char123LocaleChar125rootLayoutRouteRouteChildren: Char123LocaleChar125rootLayoutRouteRouteChildren =
  {
    Char123LocaleChar125rootLayoutauthRouteRoute:
      Char123LocaleChar125rootLayoutauthRouteRouteWithChildren,
    Char123LocaleChar125rootLayoutIndexRoute:
      Char123LocaleChar125rootLayoutIndexRoute,
    Char123LocaleChar125rootLayoutAboutIndexRoute:
      Char123LocaleChar125rootLayoutAboutIndexRoute,
    Char123LocaleChar125rootLayoutChangelogIndexRoute:
      Char123LocaleChar125rootLayoutChangelogIndexRoute,
    Char123LocaleChar125rootLayoutErrorIndexRoute:
      Char123LocaleChar125rootLayoutErrorIndexRoute,
    Char123LocaleChar125rootLayoutPlaygroundIndexRoute:
      Char123LocaleChar125rootLayoutPlaygroundIndexRoute,
    Char123LocaleChar125rootLayoutPricingIndexRoute:
      Char123LocaleChar125rootLayoutPricingIndexRoute,
    Char123LocaleChar125rootLayoutPrivacyPolicyIndexRoute:
      Char123LocaleChar125rootLayoutPrivacyPolicyIndexRoute,
    Char123LocaleChar125rootLayoutStatusIndexRoute:
      Char123LocaleChar125rootLayoutStatusIndexRoute,
    Char123LocaleChar125rootLayoutTermsOfServiceIndexRoute:
      Char123LocaleChar125rootLayoutTermsOfServiceIndexRoute,
  }

const Char123LocaleChar125rootLayoutRouteRouteWithChildren =
  Char123LocaleChar125rootLayoutRouteRoute._addFileChildren(
    Char123LocaleChar125rootLayoutRouteRouteChildren,
  )

interface Char123LocaleChar125RouteRouteChildren {
  Char123LocaleChar125adminLayoutRouteRoute: typeof Char123LocaleChar125adminLayoutRouteRouteWithChildren
  Char123LocaleChar125centeredLayoutRouteRoute: typeof Char123LocaleChar125centeredLayoutRouteRouteWithChildren
  Char123LocaleChar125consoleLayoutRouteRoute: typeof Char123LocaleChar125consoleLayoutRouteRouteWithChildren
  Char123LocaleChar125rootLayoutRouteRoute: typeof Char123LocaleChar125rootLayoutRouteRouteWithChildren
}

const Char123LocaleChar125RouteRouteChildren: Char123LocaleChar125RouteRouteChildren =
  {
    Char123LocaleChar125adminLayoutRouteRoute:
      Char123LocaleChar125adminLayoutRouteRouteWithChildren,
    Char123LocaleChar125centeredLayoutRouteRoute:
      Char123LocaleChar125centeredLayoutRouteRouteWithChildren,
    Char123LocaleChar125consoleLayoutRouteRoute:
      Char123LocaleChar125consoleLayoutRouteRouteWithChildren,
    Char123LocaleChar125rootLayoutRouteRoute:
      Char123LocaleChar125rootLayoutRouteRouteWithChildren,
  }

const Char123LocaleChar125RouteRouteWithChildren =
  Char123LocaleChar125RouteRoute._addFileChildren(
    Char123LocaleChar125RouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125RouteRoute: Char123LocaleChar125RouteRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiHealthLiveRoute: ApiHealthLiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
