import process from "node:process";

import { createEnv } from "@t3-oss/env-core";
import { isProduction } from "std-env";
import { z } from "zod";

export const ENV_WEB_SERVER = createEnv({
  emptyStringAsUndefined: true,
  runtimeEnv: process.env,
  server: {
    NODE_ENV: z.enum(["development", "production"]).default("development"),
    // Attach CSP, HSTS, and related headers on HTML document responses.
    SECURITY_HEADERS_ENABLED: z.stringbool().default(isProduction),
    SECURITY_CSP_REPORT_ONLY: z.stringbool().default(false),
    SECURITY_CSP_REPORT_URI: z.url().optional(),
    SOURCE_COMMIT: z.string().min(1).default("unknown"), // autogenerated by Coolify, needs to be manually set otherwise
    IS_BUILD: z.stringbool().default(false) // set to 'true' during build, can be used to conditionally disable features that should only run during runtime and not during build/prerendering
  }
});
