import process from "node:process";

import { createEnv } from "@t3-oss/env-core";
import { isProduction } from "std-env";
import { z } from "zod";

import { isWeakAuthSecret } from "#@/server/auth-secret";
import { assertProductionRuntimeGuards } from "#@/server/production-guards";

export const ENV_SERVER = createEnv({
  emptyStringAsUndefined: true,
  runtimeEnv: process.env,
  server: {
    VITE_SERVER_URL: isProduction ? z.url() : z.url().default("http://localhost:5000/server"),
    VITE_WEB_URL: isProduction ? z.url() : z.url().default("http://localhost:3000"),
    DATABASE_URL: z.string().min(1),
    // Set false when connecting through a transaction-mode pooler (PgBouncer/Supabase pooler).
    DATABASE_PREPARED_STATEMENTS: z.stringbool().default(true),
    DATABASE_MAX_CONNECTIONS: z.coerce.number().int().positive().default(10),
    BETTER_AUTH_SECRET: z.string().min(32),
    NODE_ENV: z.enum(["development", "production"]).default("development"),
    // Require verified email before sign-in in production unless explicitly disabled.
    REQUIRE_EMAIL_VERIFICATION: z.stringbool().default(isProduction),
    // Trust X-Forwarded-For / X-Real-IP for auth rate limits (enable behind a trusted reverse proxy).
    TRUST_PROXY_HEADERS: z.stringbool().default(false),
    // Allow process-local cache/rate-limit fallback in production (single-instance deploys only).
    ALLOW_SINGLE_INSTANCE_FALLBACK: z.stringbool().default(false),
    // Attach CSP, HSTS, and related headers on API responses.
    SECURITY_HEADERS_ENABLED: z.stringbool().default(isProduction),
    // Emit Content-Security-Policy-Report-Only instead of enforcing CSP.
    SECURITY_CSP_REPORT_ONLY: z.stringbool().default(false),
    // Optional CSP violation report collector (report-uri / report-to legacy form).
    SECURITY_CSP_REPORT_URI: z.url().optional(),
    SOURCE_COMMIT: z.string().min(1).default("unknown"), // autogenerated by Coolify, needs to be manually set otherwise
    ENABLE_OPEN_API_DOCS: z.stringbool().default(false),
    IS_BUILD: z.stringbool().default(false), // set to 'true' during build, can be used to conditionally disable features that should only run during runtime and not during build/prerendering
    // Comma-separated emails granted the platform-admin role on sign-up.
    // Leave empty to fall back to "first registered user becomes admin".
    PLATFORM_ADMIN_EMAILS: z.string().default(""),
    // Redis powers shared cache and background queues. Leave empty to use
    // process-local cache only and disable queue producers/workers.
    REDIS_URL: z.url().optional(),
    CACHE_PREFIX: z.string().min(1).default("saasweave"),
    CACHE_DEFAULT_TTL_SECONDS: z.coerce.number().int().positive().default(300),
    QUEUE_PREFIX: z.string().min(1).default("saasweave"),
    WORKER_CONCURRENCY: z.coerce.number().int().positive().default(5),
    WORKER_CONCURRENCY_DATA_EXPORT: z.coerce.number().int().positive().optional(),
    WORKER_CONCURRENCY_BATCH_JOBS: z.coerce.number().int().positive().optional(),
    WORKER_CONCURRENCY_WEBHOOKS: z.coerce.number().int().positive().optional(),
    // Stripe billing. Leave STRIPE_SECRET_KEY empty to run the console in
    // sample-billing mode; set it (test key) to activate live subscriptions.
    STRIPE_SECRET_KEY: z.string().default(""),
    STRIPE_WEBHOOK_SECRET: z.string().default(""),
    // JSON map of plan id -> { monthly, annual } Stripe price ids, e.g.
    // {"growth":{"monthly":"price_...","annual":"price_..."}}
    STRIPE_PRICES: z.string().default("{}"),
    // JSON map of usage metric -> Stripe billing meter event_name, e.g.
    // {"ai_tokens":"ai_tokens","api_calls":"api_calls"}
    STRIPE_METERS: z.string().default("{}"),
    // Transactional email. "console" (default) logs emails instead of sending,
    // so the template runs with no config. Set "resend" (+ RESEND_API_KEY) or
    // "smtp" (+ SMTP_URL, e.g. smtp://user:pass@host:587) to send for real.
    MAIL_PROVIDER: z.enum(["console", "resend", "smtp"]).default("console"),
    MAIL_FROM: z.string().default("SaaSWeave <hello@saasweave.io>"),
    RESEND_API_KEY: z.string().default(""),
    SMTP_URL: z.string().default(""),
    // Optional OAuth providers. Leave empty to keep email/password only.
    GOOGLE_CLIENT_ID: z.string().default(""),
    GOOGLE_CLIENT_SECRET: z.string().default(""),
    GITHUB_CLIENT_ID: z.string().default(""),
    GITHUB_CLIENT_SECRET: z.string().default(""),
    // Local disk media storage (dev default). Objects are served from MEDIA_PUBLIC_BASE_URL.
    MEDIA_UPLOAD_DIR: z.string().min(1).default(".uploads"),
    MEDIA_PUBLIC_BASE_URL: z.string().url().default("http://localhost:5000/server/media"),
    // MinIO / S3-compatible object storage. When set, uploads use files-sdk presigned URLs.
    MINIO_ENDPOINT: z.string().default(""),
    MINIO_BUCKET: z.string().default(""),
    MINIO_ACCESS_KEY_ID: z.string().default(""),
    MINIO_SECRET_ACCESS_KEY: z.string().default(""),
    MINIO_PUBLIC_BASE_URL: z.string().default(""),
    // BullMQ cron for maintenance jobs (invitation expiry).
    WORKER_SCHEDULE_INVITATION_CRON: z.string().min(1).default("0 3 * * *"),
    WORKER_SCHEDULE_MRR_SNAPSHOT_CRON: z.string().min(1).default("0 2 * * *"),
    WORKER_SCHEDULE_STORAGE_CLEANUP_CRON: z.string().min(1).default("30 4 * * *"),
    WORKER_SCHEDULE_DATA_RETENTION_CRON: z.string().min(1).default("0 5 * * *"),
    WORKER_SCHEDULE_PLATFORM_ANALYTICS_CRON: z.string().min(1).default("15 2 * * *"),
    WORKER_HEALTH_PORT: z.coerce.number().int().positive().default(9100),
    METRICS_ENABLED: z.stringbool().default(false),
    METRICS_BEARER_TOKEN: z.string().min(32).optional(),
    OTEL_TRACE_SAMPLE_RATE: z.coerce.number().min(0).max(1).default(0.1),
    RETENTION_PURGE_DRY_RUN: z.stringbool().default(false),
    RETENTION_LEGAL_HOLD_ORG_IDS: z.string().default(""),
    BACKUP_RESTORE_ALLOW_REMOTE: z.stringbool().default(false)
  },
  onValidationError: (error) => {
    console.debug("Invalid environment variables:", error);
    throw new Error("Invalid environment variables");
  },
  onInvalidAccess: (key) => {
    throw new Error(`Attempted to access invalid env key: ${key}`);
  }
});

if (
  !ENV_SERVER.IS_BUILD &&
  ENV_SERVER.NODE_ENV === "production" &&
  isWeakAuthSecret(ENV_SERVER.BETTER_AUTH_SECRET)
) {
  throw new Error(
    "BETTER_AUTH_SECRET is a known placeholder or too weak for production. Run `vp run auth:secret` and set a unique value."
  );
}

if (
  !ENV_SERVER.IS_BUILD &&
  ENV_SERVER.NODE_ENV === "production" &&
  !ENV_SERVER.REDIS_URL &&
  !ENV_SERVER.ALLOW_SINGLE_INSTANCE_FALLBACK
) {
  throw new Error(
    "REDIS_URL is required in production for shared cache and rate limits across replicas. Set REDIS_URL or ALLOW_SINGLE_INSTANCE_FALLBACK=true for intentional single-instance deploys only."
  );
}

if (
  !ENV_SERVER.IS_BUILD &&
  ENV_SERVER.NODE_ENV === "production" &&
  !ENV_SERVER.REDIS_URL &&
  ENV_SERVER.ALLOW_SINGLE_INSTANCE_FALLBACK
) {
  console.debug(
    "[ENV_SERVER] ALLOW_SINGLE_INSTANCE_FALLBACK is enabled without REDIS_URL — cache and rate limits are per-process only and will not be shared across replicas."
  );
}

if (!ENV_SERVER.IS_BUILD && ENV_SERVER.METRICS_ENABLED && !ENV_SERVER.METRICS_BEARER_TOKEN) {
  throw new Error("METRICS_ENABLED requires METRICS_BEARER_TOKEN with at least 32 characters.");
}

assertProductionRuntimeGuards(ENV_SERVER);
